/**
 * AI Prompt Building and Response Parsing
 *
 * Contains prompt templates and parsing logic for AI-generated flashcards.
 *
 * @module services/ai/prompts
 */

import type { Highlight, Collection, QuestionType } from '$lib/types';

/**
 * A question generated by AI before user approval
 */
export interface GeneratedQuestion {
	/** Source highlight ID */
	highlightId: string;
	/** Type of question generated */
	questionType: QuestionType;
	/** Question text */
	question: string;
	/** Answer text */
	answer: string;
	/** Cloze text with deletion markers (only for cloze type) */
	clozeText?: string;
	/** AI confidence score (0-1) */
	confidence: number;
}

/**
 * Instructions for each question type, included in the generation prompt
 */
const typeInstructions: Record<QuestionType, string> = {
	cloze: `
CLOZE DELETIONS:
- Remove a key term or phrase that tests understanding
- The blank should be specific enough to have one clear answer
- Keep surrounding context meaningful
- Format: "The {{c1::answer}} is important because..."
- Only create one cloze deletion per question`,

	definition: `
DEFINITION QUESTIONS:
- Ask "What is [term]?" or "Define [concept]"
- Answer should be concise but complete
- Focus on terms the reader likely wants to remember
- Keep answers under 2 sentences`,

	conceptual: `
CONCEPTUAL QUESTIONS:
- Ask "Why" or "How" questions
- Test understanding, not just recall
- Answer should explain the reasoning
- Avoid yes/no questions`
};

/**
 * Builds the complete prompt for question generation
 *
 * @param highlights - Highlights to generate questions from
 * @param questionTypes - Types of questions to include
 * @param collection - Parent collection for context (title, author)
 * @returns Complete prompt string for the AI
 */
export function buildGenerationPrompt(
	highlights: Highlight[],
	questionTypes: QuestionType[],
	collection: Collection
): string {
	const selectedInstructions = questionTypes.map((t) => typeInstructions[t]).join('\n\n');

	return `You are helping a reader retain knowledge from "${collection.title}"${collection.author ? ` by ${collection.author}` : ''}.

Generate study questions from the following highlights. Create 1-3 questions per highlight based on how much meaningful content it contains.

${selectedInstructions}

GUIDELINES:
- Questions should test genuine understanding, not trivial details
- Answers must be found in or directly implied by the highlight
- Skip highlights that are too vague or don't contain learnable content
- For each question, rate your confidence (0-1) that it's high quality
- Prefer cloze deletions when possible as they're most effective for memory
- Keep questions concise and focused

OUTPUT FORMAT (JSON array):
[
  {
    "highlightId": "uuid",
    "questionType": "cloze" | "definition" | "conceptual",
    "question": "...",
    "answer": "...",
    "clozeText": "... {{c1::answer}} ..." (only for cloze type),
    "confidence": 0.85
  }
]

HIGHLIGHTS:
${highlights
	.map(
		(h) => `
---
ID: ${h.id}
Text: "${h.text}"
${h.chapter ? `Chapter: ${h.chapter}` : ''}
${h.contextBefore ? `Context before: "${h.contextBefore}"` : ''}
${h.contextAfter ? `Context after: "${h.contextAfter}"` : ''}
`
	)
	.join('\n')}

Generate questions now. Output ONLY the JSON array, no other text:`;
}

/**
 * Builds message array for OpenAI Chat Completions API
 *
 * @param prompt - User prompt content
 * @returns Messages array with system and user messages
 */
export function buildOpenAIMessages(prompt: string) {
	return [
		{
			role: 'system' as const,
			content:
				'You are an expert educational content creator specializing in spaced repetition flashcards. You create high-quality questions that test understanding and aid memory retention. Always output valid JSON.'
		},
		{
			role: 'user' as const,
			content: prompt
		}
	];
}

/**
 * Builds message array for Anthropic Messages API
 *
 * @param prompt - User prompt content
 * @returns Messages array with user message
 */
export function buildAnthropicMessages(prompt: string) {
	return [
		{
			role: 'user' as const,
			content: prompt
		}
	];
}

/**
 * Parses AI response content into structured questions
 *
 * Handles various response formats:
 * - Plain JSON array
 * - JSON wrapped in markdown code blocks
 * - JSON with surrounding text
 *
 * @param content - Raw AI response content
 * @returns Array of valid generated questions
 */
export function parseGeneratedQuestions(content: string): GeneratedQuestion[] {
	let jsonStr = content.trim();

	// Handle if wrapped in markdown code block
	const jsonMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
	if (jsonMatch) {
		jsonStr = jsonMatch[1];
	}

	// Handle if there's text before/after the JSON
	const arrayMatch = jsonStr.match(/\[[\s\S]*\]/);
	if (arrayMatch) {
		jsonStr = arrayMatch[0];
	}

	try {
		const questions = JSON.parse(jsonStr);

		if (!Array.isArray(questions)) {
			throw new Error('Response is not an array');
		}

		// Filter to only valid questions with all required fields
		return questions.filter(
			(q) =>
				q.highlightId &&
				q.questionType &&
				q.question &&
				q.answer &&
				typeof q.confidence === 'number'
		);
	} catch {
		return [];
	}
}
