// This file will be auto-generated by: pnpm db:types
// For now, provide a placeholder type

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json | undefined }
	| Json[];

export interface Database {
	public: {
		Tables: {
			profiles: {
				Row: {
					id: string;
					display_name: string | null;
					daily_review_goal: number;
					preferred_question_types: string[];
					theme: string;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					display_name?: string | null;
					daily_review_goal?: number;
					preferred_question_types?: string[];
					theme?: string;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					display_name?: string | null;
					daily_review_goal?: number;
					preferred_question_types?: string[];
					theme?: string;
					created_at?: string;
					updated_at?: string;
				};
			};
			api_keys: {
				Row: {
					id: string;
					user_id: string;
					provider: string;
					encrypted_key: string;
					model: string;
					is_active: boolean;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					provider: string;
					encrypted_key: string;
					model: string;
					is_active?: boolean;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					provider?: string;
					encrypted_key?: string;
					model?: string;
					is_active?: boolean;
					created_at?: string;
				};
			};
			collections: {
				Row: {
					id: string;
					user_id: string;
					title: string;
					author: string | null;
					source_type: string;
					source_url: string | null;
					cover_image_url: string | null;
					highlight_count: number;
					card_count: number;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					title: string;
					author?: string | null;
					source_type: string;
					source_url?: string | null;
					cover_image_url?: string | null;
					highlight_count?: number;
					card_count?: number;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					title?: string;
					author?: string | null;
					source_type?: string;
					source_url?: string | null;
					cover_image_url?: string | null;
					highlight_count?: number;
					card_count?: number;
					created_at?: string;
					updated_at?: string;
				};
			};
			highlights: {
				Row: {
					id: string;
					collection_id: string;
					user_id: string;
					text: string;
					note: string | null;
					chapter: string | null;
					page_number: number | null;
					location_percent: number | null;
					context_before: string | null;
					context_after: string | null;
					has_cards: boolean;
					is_archived: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					collection_id: string;
					user_id: string;
					text: string;
					note?: string | null;
					chapter?: string | null;
					page_number?: number | null;
					location_percent?: number | null;
					context_before?: string | null;
					context_after?: string | null;
					has_cards?: boolean;
					is_archived?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					collection_id?: string;
					user_id?: string;
					text?: string;
					note?: string | null;
					chapter?: string | null;
					page_number?: number | null;
					location_percent?: number | null;
					context_before?: string | null;
					context_after?: string | null;
					has_cards?: boolean;
					is_archived?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			tags: {
				Row: {
					id: string;
					user_id: string;
					name: string;
					color: string | null;
				};
				Insert: {
					id?: string;
					user_id: string;
					name: string;
					color?: string | null;
				};
				Update: {
					id?: string;
					user_id?: string;
					name?: string;
					color?: string | null;
				};
			};
			highlight_tags: {
				Row: {
					highlight_id: string;
					tag_id: string;
				};
				Insert: {
					highlight_id: string;
					tag_id: string;
				};
				Update: {
					highlight_id?: string;
					tag_id?: string;
				};
			};
			cards: {
				Row: {
					id: string;
					highlight_id: string;
					user_id: string;
					question_type: string;
					question: string;
					answer: string;
					cloze_text: string | null;
					is_ai_generated: boolean;
					ai_confidence: number | null;
					stability: number;
					difficulty: number;
					elapsed_days: number;
					scheduled_days: number;
					reps: number;
					lapses: number;
					state: string;
					last_review: string | null;
					due: string;
					is_suspended: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					highlight_id: string;
					user_id: string;
					question_type: string;
					question: string;
					answer: string;
					cloze_text?: string | null;
					is_ai_generated?: boolean;
					ai_confidence?: number | null;
					stability?: number;
					difficulty?: number;
					elapsed_days?: number;
					scheduled_days?: number;
					reps?: number;
					lapses?: number;
					state?: string;
					last_review?: string | null;
					due?: string;
					is_suspended?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					highlight_id?: string;
					user_id?: string;
					question_type?: string;
					question?: string;
					answer?: string;
					cloze_text?: string | null;
					is_ai_generated?: boolean;
					ai_confidence?: number | null;
					stability?: number;
					difficulty?: number;
					elapsed_days?: number;
					scheduled_days?: number;
					reps?: number;
					lapses?: number;
					state?: string;
					last_review?: string | null;
					due?: string;
					is_suspended?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			reviews: {
				Row: {
					id: string;
					card_id: string;
					user_id: string;
					rating: string;
					stability_before: number;
					difficulty_before: number;
					state_before: string;
					duration_ms: number | null;
					reviewed_at: string;
				};
				Insert: {
					id?: string;
					card_id: string;
					user_id: string;
					rating: string;
					stability_before: number;
					difficulty_before: number;
					state_before: string;
					duration_ms?: number | null;
					reviewed_at?: string;
				};
				Update: {
					id?: string;
					card_id?: string;
					user_id?: string;
					rating?: string;
					stability_before?: number;
					difficulty_before?: number;
					state_before?: string;
					duration_ms?: number | null;
					reviewed_at?: string;
				};
			};
			pending_questions: {
				Row: {
					id: string;
					highlight_id: string;
					user_id: string;
					question_type: string;
					question: string;
					answer: string;
					cloze_text: string | null;
					ai_confidence: number | null;
					status: string;
					created_at: string;
				};
				Insert: {
					id?: string;
					highlight_id: string;
					user_id: string;
					question_type: string;
					question: string;
					answer: string;
					cloze_text?: string | null;
					ai_confidence?: number | null;
					status?: string;
					created_at?: string;
				};
				Update: {
					id?: string;
					highlight_id?: string;
					user_id?: string;
					question_type?: string;
					question?: string;
					answer?: string;
					cloze_text?: string | null;
					ai_confidence?: number | null;
					status?: string;
					created_at?: string;
				};
			};
		};
		Views: {};
		Functions: {};
		Enums: {};
	};
}
